Repository newrelic/nri-elasticsearch, pull requests merged in 2019-02, with the labels that each got.

#39 Added license files
  .papers_config.yml
  papers_manifest.yml
Labels: risk:none

#42 Bumped Plugin Version, Node naming change
  CHANGELOG.md
  elasticsearch-definition.yml
  src/elasticsearch.go
  src/inventory.go
  src/inventory_definition.go
  src/inventory_test.go
  src/metrics.go
  src/testdata/good-inventory.json.golden
  src/testdata/good-nodes-local.json.golden
  src/testdata/nodeStatsMetricsResult.json.golden
Labels: risk:low

#44 Added Dockerfile
  Dockerfile
Labels: enhancement, risk:none

#46 Updated Dockerfile
  Dockerfile
Labels: enhancement, risk:none
